### ISSUE TITLE
Integrate APIs

### ISSUE THREAD

**Issue by tudims** [edwisely-ai/Tech#66]
- [x] Access to the database

- [x] Schema for API 

- [x] Access to AWS

- [x] Faculty Python Code Understanding.

- [x]  Integrate API

**Comment by himaedw** [comment]
@tudims  verify this issue

**Comment by tudims** [comment]
How do I verify Hima?

Thanks,
Yash




*Yashwanth Tudimilla *
Co-Founder, Edwisely

799 516 1950 | ***@***.*** ***@***.***>

www.edwisely.com | Skype: tudimilla

819/1, Manjeera Majestic Commercial,
JNTU Road, KPHB, Hyderabad -72

**Comment by himaedw** [comment]
We will have a meet on this!
