### ISSUE TITLE
Staging EC2 Nginx and LightSail WordPress  instance connection

### ISSUE THREAD

**Issue by himaedw** [edwisely-ai/Tech#89]

**Comment by himaedw** [comment]
Staging EC2 Successfully redirected to Lightsail WordPress instance. But Lightsail WordPress instance is not showing "/blog/" subdirectory. Tried different configurations and moved to a new approach. We used the DNS name as "beta.edwisely.com"

Here's a Summary!

- ✓ beta.edwisely.com is working
- ✕ beta.edwisely.com/blog is not working

**Comment by tudims** [comment]
Decided to go ahead with blog.edwisely.com instead of the subfolder approach of edwisely.com/blog 

Learning: Going forward check for the feasibility of a task prior to spending time in it. Technical expert needs to spend time in evaluating and be responsible if it doesn't go through.
